spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iqltest
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  flyway:
    user: postgres
    password: password
    schemas: public
    enabled: true
